### ISSUE TITLE
Enabling use_glsl_to_spirv feature makes it failt to build

### ISSUE THREAD

**Issue by kvark** [Ruddle/oxidator#2]
Because it conflicts with `use_spirv`. I think the logic could be smarter and consider the `use_glsl_to_spirv` to override the other options, making them truly commutative as expected by `cargo`.

**Comment by Ruddle** [comment]
Thanks for the advice. I knew I was doing something weird with the feature flags ^^. I will look up how it is supposed to be done and fix that.
