### ISSUE TITLE
Arrow.vert is not writing the world_pos output

### ISSUE THREAD

**Issue by kvark** [Ruddle/oxidator#3]
In https://github.com/Ruddle/oxidator/blob/559f67d7cc399675ccb1c6009d40a7585edb9c82/src/shader/arrow.vert#L50
```
//    world_pos = a_Pos.xyz +a_off;
```
This output is expected by the fragment shader, so the current shader is incorrect (and fails to build on some platforms).

**Comment by Ruddle** [comment]
Thanks
